nombre = input("ingrese su nombre")
edad = int(input("ingrese su edad"))
ciudad = input("cual es su ciudad")
horas_trabajadas = float(input("cuantas horas trabajo"))
salario_base =int(input("valor hora"))
